#!/bin/sh

if [ $(id -u) -gt 0 ];
then
	echo "You must be root to run this script." >&2
	exit 1
fi

src=/etc/network/interfaces.d
tmp=/etc/network/.interfaces.tmp
dst=/etc/network/interfaces

> "$tmp"

find "$src" -type f ! -name ".*" | sort | while read file
do
	basename=$(basename "$file")

	if echo "$basename" | grep -v '^00-';
	then
		echo "# $basename" >> "$tmp"
	fi

	cat "$file" >> "$tmp"
	echo "" >> "$tmp"
done

mv -f "$tmp" "$dst"
rm -f "$tmp"

/etc/init.d/networking restart
