#!/bin/sh

if [ $(id -u) -gt 0 ];
then
	echo "You must be root to run this script." >&2
	exit 1
fi

src=/etc/network/interfaces.d
dst=/etc/.interfaces.tmp

> "$dst"

find "$src" -type f ! -name ".*" | sort | while read file
do
	cat "$file" >> "$dst"
done
